project:
  type: book
  output-dir: docs

book:
  title: "rethinking2020_ex"
  author: "François Lefebvre"
  date: "2022-12-12"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

